name: generate animation

on:
  schedule:
    - cron: "0 0 * * *" # roda todo dia à meia-noite
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: Platane/snk@v3
        with:
          github_user_name: rakellkizz
          outputs: |
            dist/github-snake.svg
            dist/github-snake-dark.svg
