name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *"  # Executa todo dia à meia-noite
  workflow_dispatch:  # Permite execução manual

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v2

      - name: Gerar a Snake Animation
        uses: Platane/snk@v3
        with:
          github_user_name: rakellkizz
          outputs: |
            github-contribution-grid-snake.svg
            github-contribution-grid-snake-dark.svg?palette=github-dark

      - name: Commit e Push
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add .
          git commit -m "Atualizando animação da cobra"
          git push
     
