name: GitHub Snake Game

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Run a script
        run: |
          echo "GitHub Snake Game workflow is running!"
          # Coloque aqui os comandos necessários para rodar seu jogo Snake ou outro script
