name: Generate Snake Game

on:
  schedule:
    - cron: "0 0 * * *"  # Executa todo dia à meia-noite UTC
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v4

      - name: Gerar Snake Game SVG
        uses: Platane/snk@v3
        with:
          github_user_name: rakellkizz
          outputs: |
            ./dist/github-snake.svg
            ./dist/github-snake-dark.svg?palette=github-dark

      - name: Publicar no GitHub Pages (branch output)
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          publish_branch: output
