name: Generate Snake Game

on:
  schedule:
    - cron: "0 0 * * *"  # Executa todo dia à meia-noite UTC
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v4

      - name: Gerar Snake Game SVG
        uses: Platane/snk@v3
        with:
          github_user_name: rakellkizz
          outputs: |
            ./github-snake.svg
            ./github-snake-dark.svg?palette=github-dark

      - name: Commit e Push do resultado
        uses: EndBug/add-and-commit@v9
        with:
          message: "🐍 Atualiza a cobrinha (contribuições)"
          add: "*.svg"
