name: Update GitHub Stats Cards

on:
  schedule:
    - cron: "0 6 * * *"

  workflow_dispatch:

permissions:
  contents: write

jobs:
  generate-stats:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create profile directory
        run: mkdir -p profile

      - name: Generate GitHub Stats
        run: |
          curl -L \
            --retry 5 \
            --retry-delay 10 \
            --fail \
            "https://github-readme-stats.vercel.app/api?username=rakellkizz&show_icons=true&theme=dracula&include_all_commits=true&count_private=true&hide_border=false" \
            -o profile/github-stats.svg

      - name: Generate Top Languages
        run: |
          curl -L \
            --retry 5 \
            --retry-delay 10 \
            --fail \
            "https://github-readme-stats.vercel.app/api/top-langs/?username=rakellkizz&layout=compact&theme=tokyonight" \
            -o profile/top-langs.svg

      - name: Commit generated cards
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"

          git add profile/github-stats.svg
          git add profile/top-langs.svg

          if git diff --cached --quiet; then
            echo "Nenhuma alteração encontrada."
            exit 0
          fi

          git commit -m "Atualiza cards de estatísticas do perfil"
          git push
